
// USER REDUCER
export const SET_AUTHENTICATED ='SET_AUTHENTICATED'
export const SET_UNAUTHENTICATED ='SET_UNAUTHENTICATED'
export const SET_USER ='SET_USER '
export const LOADING_USER ='LOADING_USER'
export const UPDATE_USER_IMG = "UPDATE_USER_IMG";   
export const UPDATE_PROFILE = "UPDATE_PROFILE"; 
export const OFF_UPDATE = "OFF_UPDATE";

// UI REDUCER TYPE
export const SET_ERRORS ='SET_ERRORS'
export const LOADING_UI ='LOADING_UI'
export const CLEAR_ERRORS ='CLEAR_ERRORS'
export const MENU_TRUE ='MENU_TRUE'
export const MENU_FALSE ='MENU_FALSE'

// DATA REDUCER
export const ADD_BOOK ='ADD_BOOK'
export const BOOK_ERROR='BOOK_ERROR'
export const ADD_IMG='ADD_IMG'
export const ADDING="ADDING"
export const ADD_USER_BOOKS ="ADD_USER_BOOKS"
export const ADD_USER_BOOKS_FAIL ="ADD_USER_BOOKS_FAIL" 
export const UPDATE_BOOK = "UPDATE_BOOK";
export const DELETE_BOOK = "DELETE_BOOK";
export const GET_ALL_BOOK = "GET_ALL_BOOK";






